//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoneBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.peopleInDirectory = new HashSet<peopleInDirectory>();
        }
    
        public int id { get; set; }


        [Required(ErrorMessage = "Bu alan gerekli!")]
        [Display(Name = "Ad Soyad")]
        public string fullName { get; set; }


        [Required(ErrorMessage = "Bu alan gerekli!")]
        [Display(Name = "Kullanýcý Adý")]
        public string userName { get; set; }


        [Required(ErrorMessage = "Bu alan gerekli!")]
        [Display(Name = "Þifre")]
        [DataType(DataType.Password)]
        public string password { get; set; }


        [Required(ErrorMessage = "Bu alan gerekli!")]
        [Display(Name = "Þifre Tekrar")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("password",ErrorMessage ="Þifreler uyuþmuyor!")]
        public string rePassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peopleInDirectory> peopleInDirectory { get; set; }
    }
}
